name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: run tests
        run: forge test --ffi -vvvv